apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: currency-conversion-service
  name: currency-conversion-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency-conversion-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: currency-conversion-service
    spec:
      containers:
      - image: ayush1608/currency-conversion-service:0.0.12-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: currency-conversion-service
        env:
          - name: CURRENCY_EXCHANGE_SERVICE_URI
            value: http://currency-exchange-service # The value should match service name created on k8s cluster
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: currency-conversion-service
  name: currency-conversion-service
  namespace: default
spec:
  ports:
    - port: 8100
      protocol: TCP
      targetPort: 8100
  selector:
    app: currency-conversion-service
  sessionAffinity: None
  type: LoadBalancer